language: d

sudo: false

d:
  - dmd #-2.079.0
  - dmd-2.078.3
  - dmd-2.071.0
  - dmd-2.070.2
  - dmd-2.069.2
  - dmd-2.068.1
  - dmd-2.067.1
  - ldc-0.16.1
  - ldc-0.17.1
  - ldc-1.0.0-beta2
  - ldc #-1.7.0
  - gdc #-5.2.0

script:
  - dub test --compiler=$DC || exit 1
